version: '3'

services:
  nest:
    container_name: nest
    depends_on:
      - db
    networks:
      - net
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/workspace
  db:
    container_name: db
    image: mariadb:10.7.1
    networks:
      - net
    ports:
      - '3306:3306'
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

networks:
  net:

volumes:
  dbvol:
