spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_manager?characterEncoding=utf8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 変換元、変換先のJSONプロパティの命名規則を指定
    property-naming-strategy: SNAKE_CASE